// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llajjnzilghswynmowze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsYWpqbnppbGdoc3d5bm1vd3plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNjM5NDMsImV4cCI6MjA3MTYzOTk0M30.SkIkgGW5qS59l0qz_3xPxszWw18bG5usQZ0ovGmrkGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});